### ISSUE TITLE
Discord.js Docs site Down

### ISSUE THREAD

**Issue by dskilly** [hydrabolt/discord.js-site#1]
Hi,
I think something went wrong with the new commits not entirely sure what but can't really open the docs site... or is it purposely down?
![image](https://cloud.githubusercontent.com/assets/20648461/21576627/f77c0f02-cf04-11e6-9ff6-81313913f6f2.png)

**Comment by Gawdl3y** [comment]
Waiting on js-org/dns.js.org#983.

**Comment by dskilly** [comment]
@Gawdl3y Alright, thanks for the fast reply was wondering why and being paranoid if it was something on my end XD
