### ISSUE TITLE
Clicking on the 'dispose' event on ReactionCollector sends you to the method instead

### ISSUE THREAD

**Issue by Aetheryx** [hydrabolt/discord.js-site#8]
Clicking on the dispose event [here](https://why-are-you-buying-clothes-at.the-soup.store/494288.png) on [this](https://discord.js.org/#/docs/main/master/class/ReactionCollector) page brings you to the [dispose *method*](https://why-are-you-buying-clothes-at.the-soup.store/90cac2.png), not the [*event*](https://why-are-you-buying-clothes-at.the-soup.store/b74fba.png).

**Comment by Gawdl3y** [comment]
Fixed in f3f7ee868b0da9388f78aea129897bf8482f5953.
